# Просьба отметиться на портале

Короткая работа в начале занятия (22.02.2018)

In [10]:
def f1(n):
    return [x ** 2 for x in range(1, n) if math.sin(x) > 0]

f1(100)

[1,
 4,
 9,
 49,
 64,
 81,
 169,
 196,
 225,
 361,
 400,
 441,
 676,
 729,
 784,
 1024,
 1089,
 1156,
 1444,
 1521,
 1600,
 1936,
 2025,
 2116,
 2209,
 2601,
 2704,
 2809,
 3249,
 3364,
 3481,
 3969,
 4096,
 4225,
 4900,
 5041,
 5184,
 5776,
 5929,
 6084,
 6724,
 6889,
 7056,
 7744,
 7921,
 8100,
 8281,
 9025,
 9216,
 9409]

In [17]:
def f2(n, m):
    matr = []
    for i in range(0, n):
        matr.append(range(i * m, (i + 1) * m))
        if i % 2 == 1:
            matr[i].reverse()
    return matr

f2(3, 4)

[[0, 1, 2, 3], [7, 6, 5, 4], [8, 9, 10, 11]]

In [60]:
def f3(string):
    cnt_rus = 0
    cnt_eng = 0
    for c in string:
        if 'a' <= c and c <= 'z' or 'A' <= c and c <= 'Z':
            cnt_eng = cnt_eng + 1
        if u'а' <= c and c <= u'я' or u'А' <= c and c <= u'Я':
            cnt_rus = cnt_rus + 1
    
    print cnt_rus
    print cnt_eng
    
    if cnt_rus > cnt_eng:
        print "Russian"
    elif cnt_rus < cnt_eng:
        print "English"
    else:
        print "Equal"
        
f3(u"ййййййййadasdВasd")

9
8
Russian


In [1]:
%matplotlib inline
import matplotlib.pyplot as plt
import numpy as np

# 2.1. Numpy ndarray - создание

Numpy - пакет для векторизованных вычислений в Python'e. Основной объект в numpy - ndarray, который располагается напрерывно в памяти и позволяет производить быстрые вычисления (конструктор для ndarray - array, так как последний не является массивом, то мы будем использовать array и ndarray как синонимы без всякого риска).

В чем преимущества массива в numpy перед списком в Питоне?

* статическая типизация и гомогенность;
* возможность компиляции функций, работающих с статистически типизированными объектами;
* как следствие, эффективное использование RAM и CPU;
* broadcasting (рассмотрим далее).

То, что элементы array расположены последовательно означает, что следовать за a[i] элементом массива в памяти будет элемент a[i+1]. Каждый элемент занимает, разумеется, itemsize байтов.

In [2]:
a = np.array([1,2,3,4], dtype=np.int16)

In [3]:
a.shape

(4,)

In [61]:
a = np.array([[1, 2], [3, 4]])

In [62]:
a.size

4

In [63]:
a.shape

(2, 2)

In [64]:
a.dtype

dtype('int64')

In [65]:
a.itemsize

8

In [66]:
a.nbytes

32

In [67]:
np.size(a)

4

In [68]:
np.shape(a)

(2, 2)

In [69]:
np.lookfor('create array')

Search results for 'create array'
---------------------------------
numpy.array
    Create an array.
numpy.memmap
    Create a memory-map to an array stored in a *binary* file on disk.
numpy.diagflat
    Create a two-dimensional array with the flattened input as a diagonal.
numpy.fromiter
    Create a new 1-dimensional array from an iterable object.
numpy.partition
    Return a partitioned copy of an array.
numpy.ctypeslib.as_array
    Create a numpy array from a ctypes array or a ctypes POINTER.
numpy.ma.diagflat
    Create a two-dimensional array with the flattened input as a diagonal.
numpy.ma.make_mask
    Create a boolean mask from an array.
numpy.ctypeslib.as_ctypes
    Create and return a ctypes object from a numpy array.  Actually
numpy.ma.mrecords.fromarrays
    Creates a mrecarray from a (flat) list of masked arrays.
numpy.lib.format.open_memmap
    Open a .npy file as a memory-mapped array.
numpy.ma.MaskedArray.__new__
    Create a new masked array from scratch.
numpy.lib.ar

и IPython:

Разумеется, произвольно присваивать значения элементам массива нельзя:

In [70]:
a[0,0] = "hello"

ValueError: invalid literal for long() with base 10: 'hello'

In [71]:
a[0,0] = 100

** Тип не изменяется! **

In [72]:
a = np.arange(10, dtype=np.int)
a[0] = np.pi
a

array([3, 1, 2, 3, 4, 5, 6, 7, 8, 9])

**Создание массивов**

Создавать из списков мы уже умеем:

In [73]:
np.array([1,2,3,4], dtype=np.int16)

array([1, 2, 3, 4], dtype=int16)

Разумеется, главное - чтобы объект, корый передается конструктору, поддерживал протокол итерации.

In [74]:
np.array((1,2,3,4), dtype=np.int16)

array([1, 2, 3, 4], dtype=int16)

In [75]:
np.arange(1,10,0.5)

array([1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5, 6. , 6.5, 7. ,
       7.5, 8. , 8.5, 9. , 9.5])

In [76]:
np.linspace(0, 1, 25)

array([0.        , 0.04166667, 0.08333333, 0.125     , 0.16666667,
       0.20833333, 0.25      , 0.29166667, 0.33333333, 0.375     ,
       0.41666667, 0.45833333, 0.5       , 0.54166667, 0.58333333,
       0.625     , 0.66666667, 0.70833333, 0.75      , 0.79166667,
       0.83333333, 0.875     , 0.91666667, 0.95833333, 1.        ])

In [77]:
np.ones((3, 3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [78]:
np.zeros((3, 2))

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [79]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [80]:
np.diag(np.array([1, 2, 3, 4]))

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [81]:
x = np.array([('Rex', 9, 81.0), ('Fido', 3, 27.0)],
       dtype=[('name', 'U10'), ('age', 'i4'), ('weight', 'f4')])
x

array([(u'Rex', 9, 81.), (u'Fido', 3, 27.)],
      dtype=[('name', '<U10'), ('age', '<i4'), ('weight', '<f4')])

** Случайные массивы **

на интервале [0,1]:

In [82]:
np.random.rand(3,2)

array([[0.50755507, 0.0211933 ],
       [0.43352176, 0.44631306],
       [0.23881999, 0.83024573]])

Нормально распределенные:

In [83]:
np.random.randn(3,2)

array([[ 0.53942869,  1.52676162],
       [-3.2771929 , -1.84856065],
       [ 0.67212494, -1.49297925]])

In [84]:
np.random.randint(0, 1000, 4)

array([452, 211, 532, 635])

# 2.2. Numpy ndarray - индексы

In [85]:
A = np.random.rand(3,5)

In [86]:
A

array([[0.52230328, 0.09832853, 0.71363667, 0.88404059, 0.56705442],
       [0.99448158, 0.17873977, 0.01220009, 0.45699848, 0.93175194],
       [0.84602469, 0.47332988, 0.90255503, 0.22599553, 0.30415374]])

In [87]:
A[0,:]

array([0.52230328, 0.09832853, 0.71363667, 0.88404059, 0.56705442])

In [88]:
A[:,0]

array([0.52230328, 0.99448158, 0.84602469])

Поддерживается стандартный протокол - python slicing syntax ([lower:upper:step]) :

Slice'ы не копируют данные, по сути просто получаем view некоторых ячеек массива.

In [89]:
A[0,:]

array([0.52230328, 0.09832853, 0.71363667, 0.88404059, 0.56705442])

In [91]:
A[0,:][0:4:2]

array([0.52230328, 0.71363667])

Операция slicing создает т.н. view - то есть данные не копируются, поэтому исходный объект по адресу - mutable.

In [92]:
A[0,:][0:4:2] = [1.0, 2.5]

In [93]:
A

array([[1.        , 0.09832853, 2.5       , 0.88404059, 0.56705442],
       [0.99448158, 0.17873977, 0.01220009, 0.45699848, 0.93175194],
       [0.84602469, 0.47332988, 0.90255503, 0.22599553, 0.30415374]])

Параметры для slicing могут пропускаться:

In [94]:
A[0,:][0:4:2]

array([1. , 2.5])

In [95]:
A[0,:][0:4]

array([1.        , 0.09832853, 2.5       , 0.88404059])

In [96]:
A[0,:][:3]

array([1.        , 0.09832853, 2.5       ])

In [97]:
A[0,:][::-1]

array([0.56705442, 0.88404059, 2.5       , 0.09832853, 1.        ])

In [98]:
A[0,:][-3:]

array([2.5       , 0.88404059, 0.56705442])

<img src="http://www.scipy-lectures.org/_images/numpy_indexing.png">

** Fancy Indexing **

Этим термином обозначается индексирование с помощью массивов (или иных итерируемых конструкций).

In [99]:
row_indices = [1, 2]
A[row_indices]

array([[0.99448158, 0.17873977, 0.01220009, 0.45699848, 0.93175194],
       [0.84602469, 0.47332988, 0.90255503, 0.22599553, 0.30415374]])

In [100]:
col_indices = [1, -1]
A[row_indices, col_indices]

array([0.17873977, 0.30415374])

Возможно Булево индексирование (**Boolean indexing**):

In [105]:
B = np.array([n for n in xrange(5)])
row_mask = np.array([True, False, True, False, False])
B[row_mask]

array([0, 2])

In [102]:
row_mask = np.array([1,0,1,0,0], dtype=bool)
B[row_mask]

array([0, 2])

Это очень удобно, как вы наверняка догадались, если мы хотим отобрать данные, отвечающие определенным условиям:

In [106]:
x = np.arange(0, 10, 0.5)
x

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5, 6. ,
       6.5, 7. , 7.5, 8. , 8.5, 9. , 9.5])

In [108]:
mask = (5 < x) * (x < 7.5)
mask

array([False, False, False, False, False, False, False, False, False,
       False, False,  True,  True,  True,  True, False, False, False,
       False, False])

In [109]:
x[mask]

array([5.5, 6. , 6.5, 7. ])

<img src="http://www.scipy-lectures.org/_images/numpy_fancy_indexing.png">

Получить список индексов элементов, отвечающих заданной маске, можно с помощью **which**:

In [110]:
indices = np.where(mask)

indices

(array([11, 12, 13, 14]),)

In [111]:
x[indices]

array([5.5, 6. , 6.5, 7. ])

## TLDR:
* основной объект numpy - гомогенный массив фиксированного размера;
* для доступа к элементам массива пользуйтесь slicing и помните, что slicing создает view, а значит исходный массив может быть изменен.

# 2.3. Numpy ndarray - элементарные операции с массивами

** Broadcasting **

Концепеция broadcasting является ключевой для понимания операций с массивами. Обычно, операции с массивами производятся поэлементно. 

In [112]:
a = np.array([1.0,2.0,3.0])
b = np.array([2.0,2.0,2.0])

In [113]:
a * b

array([2., 4., 6.])

Что, если массивы разного размера? Начнем с простого - скаляр и вектор:

In [114]:
a = np.array([1.0,2.0,3.0])
b = 2.0
a * b

array([2., 4., 6.])

Все просто - скаляр словно "вырастает" (broadcasted) до размеров вектора и производится поэлементная операция (разумеется, это умозрительная аналогия - новый вектор из 2 не создается!).

Общее правило таково:

операция может произведена если размерность "крайних" осей массивов совпадает (trailing dimension), либо один из элементов является скаляром.

Пример из оффициальной документации:

In [115]:
'''

Image  (3d array): 256 x 256 x 3
Scale  (1d array):             3
Result (3d array): 256 x 256 x 3

A      (4d array):  8 x 1 x 6 x 1
B      (3d array):      7 x 1 x 5
Result (4d array):  8 x 7 x 6 x 5

'''
pass

а вот эти опреции дадут вам ошибку:

In [116]:
'''
A      (1d array):  3
B      (1d array):  4 # trailing dimensions do not match

A      (2d array):      2 x 1
B      (3d array):  8 x 4 x 3 # second from last dimensions mismatched
'''
pass

In [117]:
x = np.arange(4)
xx = x.reshape(4,1)
y = np.ones(5)
z = np.ones((3,4))

print x.shape

print y.shape

x + y

(4,)
(5,)


ValueError: operands could not be broadcast together with shapes (4,) (5,) 

In [118]:
print xx.shape
print y.shape
print (xx + y).shape
print xx + y

print '-------'

print x.shape
print z.shape
print (x + z).shape
print x + z

(4, 1)
(5,)
(4, 5)
[[1. 1. 1. 1. 1.]
 [2. 2. 2. 2. 2.]
 [3. 3. 3. 3. 3.]
 [4. 4. 4. 4. 4.]]
-------
(4,)
(3, 4)
(3, 4)
[[1. 2. 3. 4.]
 [1. 2. 3. 4.]
 [1. 2. 3. 4.]]


** Операции вида "массив - скаляр" **

In [119]:
A

array([[1.        , 0.09832853, 2.5       , 0.88404059, 0.56705442],
       [0.99448158, 0.17873977, 0.01220009, 0.45699848, 0.93175194],
       [0.84602469, 0.47332988, 0.90255503, 0.22599553, 0.30415374]])

In [120]:
A + 2

array([[3.        , 2.09832853, 4.5       , 2.88404059, 2.56705442],
       [2.99448158, 2.17873977, 2.01220009, 2.45699848, 2.93175194],
       [2.84602469, 2.47332988, 2.90255503, 2.22599553, 2.30415374]])

** Операции вида "массив - массив" **

Производятся поэлементно с учетом правил broadcasting:

In [121]:
A * A

array([[1.00000000e+00, 9.66849985e-03, 6.25000000e+00, 7.81527772e-01,
        3.21550717e-01],
       [9.88993611e-01, 3.19479055e-02, 1.48842106e-04, 2.08847611e-01,
        8.68161681e-01],
       [7.15757773e-01, 2.24041172e-01, 8.14605575e-01, 5.10739779e-02,
        9.25094967e-02]])

In [122]:
A / A

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [123]:
QQQQ = np.zeros((2, 2))
QQQQ / QQQQ

array([[nan, nan],
       [nan, nan]])

** Матричные операции**

In [124]:
A = np.random.rand(3,3)

In [125]:
np.dot(A,A)

array([[0.72450234, 0.94028892, 0.69697035],
       [0.68579901, 0.65569099, 1.02618663],
       [0.45171689, 0.37716702, 0.38464053]])

In [126]:
v = np.random.randn(3)

In [127]:
np.dot(A,v)

array([-0.01280648, -0.40159954, -0.63025677])

In [128]:
np.dot(v,v)

2.8562950940128347

Если хочется использовать по умолчанию операции из матричной алгебры, то можно использовать конструктор matrix().

In [129]:
M = np.matrix(A)

In [130]:
v1 = np.matrix(v).T

In [131]:
M.shape

(3, 3)

In [132]:
v1.shape

(3, 1)

In [133]:
v1.T * v1

matrix([[2.85629509]])

In [134]:
M * v1

matrix([[-0.01280648],
        [-0.40159954],
        [-0.63025677]])

In [135]:
A.T

array([[0.71499388, 0.2858131 , 0.3389969 ],
       [0.72409148, 0.58048634, 0.12008312],
       [0.01867644, 0.93078663, 0.51627271]])

** "Flattening" массива **

In [136]:
a = np.array([[1, 2, 3], [4, 5, 6]])

In [137]:
a.ravel()

array([1, 2, 3, 4, 5, 6])

In [138]:
a.T.ravel()

array([1, 4, 2, 5, 3, 6])

** reshape **

In [139]:
a.shape

(2, 3)

In [140]:
b = a.ravel()

In [141]:
b = b.reshape((2, 3))

In [142]:
b

array([[1, 2, 3],
       [4, 5, 6]])

** resize **

In [143]:
a = np.arange(4)

In [144]:
a.resize((8,))

In [145]:
a

array([0, 1, 2, 3, 0, 0, 0, 0])

** repeat **

In [146]:
a = np.array([[1, 2], [3, 4]])
np.repeat(a, 3)

array([1, 1, 1, 2, 2, 2, 3, 3, 3, 4, 4, 4])

In [147]:
np.tile(a, 3)

array([[1, 2, 1, 2, 1, 2],
       [3, 4, 3, 4, 3, 4]])

** concatenate **

In [148]:
a

array([[1, 2],
       [3, 4]])

In [149]:
b = np.array([[5, 6]])

In [150]:
np.concatenate((a, b), axis=0)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [151]:
np.concatenate((a, b.T), axis=1)

array([[1, 2, 5],
       [3, 4, 6]])

Что касается параметра axis, то иллюстрировать его использование можно следующим образом:

<img src="https://www.scipy-lectures.org/_images/reductions.png">

** hstack **

Название говорит само за себя - horizontal stack.

In [155]:
np.hstack((a,b.T))

array([[1, 2, 5],
       [3, 4, 6]])

In [153]:
a.shape

(2, 2)

In [156]:
b.T.shape

(2, 1)

** vstack **

In [157]:
np.vstack((a,b))

array([[1, 2],
       [3, 4],
       [5, 6]])

In [158]:
a.shape

(2, 2)

In [159]:
b.shape

(1, 2)

** Копии и view **

Мы помним, что очень важно различать копирование объекта и присваивание новой ссылки на объект. Numpy в этом смысле не отличается от списков:

In [160]:
A = np.array([[1, 2], [3, 4]])

In [161]:
B = A

In [162]:
B[0,0] = 10

In [163]:
A

array([[10,  2],
       [ 3,  4]])

Если это не тот тип поведения, который нам нужен - следует использовать np.copy():

In [164]:
B = np.copy(A)

In [165]:
B[0,0] = 100

In [166]:
A

array([[10,  2],
       [ 3,  4]])

Важно помнить, что если вы используете view массива, то копии вы не создаете!

In [167]:
a = np.arange(10)

In [168]:
b = a[::2]

In [169]:
np.may_share_memory(a, b)

True

In [170]:
c = a[::2].copy()
np.may_share_memory(a, c)

False

In [171]:
d = a.T
np.may_share_memory(a, d)

True

## TLDR:
* следует отличать копию массива и view;
* при осуществлении операций помните про правила broadcasting;
* запомните hstack и vstack.

# 2.4. Numpy - основные функции.

** Встроенные функции массива **

In [175]:
m = np.random.rand(3,3)
m

array([[0.91084975, 0.69213675, 0.04294299],
       [0.8335869 , 0.36994852, 0.936557  ],
       [0.48305288, 0.12533161, 0.96445418]])

In [194]:
m.sum()

5.358860576940926

In [177]:
m.max()

0.9644541837597798

# Всегда используйте встроенные функции!

In [185]:
a = np.random.rand(100000)

In [189]:
% timeit max(a)

100 loops, best of 3: 6.13 ms per loop


In [190]:
% timeit a.max()

The slowest run took 7.25 times longer than the fastest. This could mean that an intermediate result is being cached.
10000 loops, best of 3: 30.6 µs per loop


In [192]:
% timeit sum(a)

100 loops, best of 3: 8.29 ms per loop


In [191]:
% timeit a.sum()

The slowest run took 7.99 times longer than the fastest. This could mean that an intermediate result is being cached.
10000 loops, best of 3: 42.7 µs per loop


In [195]:
a = np.random.rand(1000000)

In [199]:
%%time
r = 0
for x in a:
    r += np.power(np.sin(x), 2)

CPU times: user 3.91 s, sys: 294 ms, total: 4.21 s
Wall time: 4 s


In [201]:
%%time
r = (np.sin(a) ** 2).sum()

CPU times: user 14.4 ms, sys: 5.73 ms, total: 20.2 ms
Wall time: 24.2 ms


In [202]:
n, m = 1000, 5000
A = np.random.random((n, m))
B = np.random.random((n, m))

In [203]:
%%time
C = np.zeros_like(A)
for i in range(n):
    for j in range(m):
        C[i,j] = A[i,j] + B[i,j]

CPU times: user 4.5 s, sys: 21.9 ms, total: 4.52 s
Wall time: 4.52 s


In [204]:
%%time
C = A + B

CPU times: user 12.5 ms, sys: 20 ms, total: 32.5 ms
Wall time: 30.7 ms


In [213]:
m = np.random.randn(3,5)
m

array([[-2.29055672, -0.37273425, -0.51349226, -0.2295845 ,  0.69775972],
       [ 0.20863087, -0.24365449, -0.40550489, -1.50897031,  1.22009902],
       [-0.33631767,  0.6954041 ,  1.2826425 ,  0.46334399,  0.06845709]])

In [214]:
m.sum(axis=0)

array([-2.41824353,  0.07901536,  0.36364535, -1.27521082,  1.98631583])

In [215]:
m.sum(axis=1)

array([-2.70860801, -0.72939981,  2.17353001])

In [216]:
m.max(axis=0)

array([0.20863087, 0.6954041 , 1.2826425 , 0.46334399, 1.22009902])

Очень полезно произведение всех элементов:

In [220]:
print m.prod(axis=1)
m.prod()

[ 0.07023001 -0.03795114 -0.00951513]


2.5360750483611414e-05

Кумулятивная сумма элементов:

In [221]:
a.cumsum() * 100

array([7.38295696e+01, 7.44265422e+01, 1.13377657e+02, ...,
       4.99901190e+07, 4.99901708e+07, 4.99902630e+07])

In [222]:
a.cumsum() * 100 / a.sum()

array([1.47687900e-04, 1.48882078e-04, 2.26799481e-04, ...,
       9.99997120e+01, 9.99998157e+01, 1.00000000e+02])

**Простые статистики**

**Среднее**

In [223]:
m.mean(axis=0)

array([-0.80608118,  0.02633845,  0.12121512, -0.42507027,  0.66210528])

In [224]:
np.mean(m, axis=0)

array([-0.80608118,  0.02633845,  0.12121512, -0.42507027,  0.66210528])

In [225]:
np.mean(a)

0.49990262980080963

In [226]:
a.mean()

0.49990262980080963

**Медиана**

In [227]:
np.median(m, axis=0)

array([-0.33631767, -0.24365449, -0.40550489, -0.2295845 ,  0.69775972])

In [228]:
np.median(a)

0.4998347415571377

** Дисперсия **

In [229]:
np.std(m, axis=0)

array([1.07299983, 0.47602663, 0.82243561, 0.81697284, 0.47083133])

In [230]:
m.std(axis=0)

array([1.07299983, 0.47602663, 0.82243561, 0.81697284, 0.47083133])

In [231]:
np.var(a)

0.08334674416540716

In [232]:
a.var()

0.08334674416540716

** Сортировка **

In [233]:
np.sort(a)

array([5.82323220e-07, 9.70059216e-07, 1.43206497e-06, ...,
       9.99996966e-01, 9.99998461e-01, 9.99999037e-01])

Функция выше возвращает отсортированную копию массива. Если нужна сортировка in-place:

In [237]:
a.sort()
a

array([7.65836792e-06, 3.62948266e-05, 3.80507650e-05, ...,
       9.99972812e-01, 9.99979113e-01, 9.99999291e-01])

In [238]:
a = np.random.rand(100000)

Также иногда бывает полезно получить только список индексов в правильном порядке:

In [239]:
np.argsort(a)

array([45267, 46978, 65190, ..., 55546, 11501, 87484])

In [240]:
np.argmax(a)

87484

In [243]:
np.argmin(a)

45267

In [244]:
np.nonzero(a)

(array([    0,     1,     2, ..., 99997, 99998, 99999]),)

** Функции для работы с матрицами **

In [245]:
m

array([[-2.29055672, -0.37273425, -0.51349226, -0.2295845 ,  0.69775972],
       [ 0.20863087, -0.24365449, -0.40550489, -1.50897031,  1.22009902],
       [-0.33631767,  0.6954041 ,  1.2826425 ,  0.46334399,  0.06845709]])

In [246]:
np.diag(m)

array([-2.29055672, -0.24365449,  1.2826425 ])

In [247]:
m.diagonal()

array([-2.29055672, -0.24365449,  1.2826425 ])

Для целого класса функций из линейной алгебры есть свой суб-модуль np.linalg.

http://docs.scipy.org/doc/numpy/reference/routines.linalg.html

In [248]:
MM = np.random.randn(9, 6)

In [249]:
U, s, V = np.linalg.svd(MM, full_matrices=False)
U.shape, V.shape, s.shape

((9, 6), (6, 6), (6,))

In [252]:
S = np.diag(s)
np.allclose(MM, np.dot(U, np.dot(S, V)))

True

** Векторизация кода **

В numpy есть встроенная функция vectorize, которая "автоматически" векторизует вашу функцию:

In [253]:
def heavyside(x):
    if x >= 0:
        return 1
    else:
        return 0

In [254]:
heavyside(np.array([-3,-2,-1,0,1,2,3]))

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [255]:
heavyside_vec = np.vectorize(heavyside)

In [256]:
heavyside_vec(np.array([-3,-2,-1,0,1,2,3]))

array([0, 0, 0, 1, 1, 1, 1])

Тем не менее, лучше сразу пишите так:

In [257]:
def heavyside(x):
    return 1 * (x >= 0)

In [258]:
heavyside(np.array([-3,-2,-1,0,1,2,3]))

array([0, 0, 0, 1, 1, 1, 1])

** Условные выражения **

Как вы уже поняли, для вектора конструкция типа if (vector) не подходит.

In [259]:
if (M > 5).any():
    print("at least one element in M is larger than 5")
else:
    print("no element in M is larger than 5")

no element in M is larger than 5


In [260]:
if (M > 5).all():
    print("all elements in M are larger than 5")
else:
    print("all elements in M are not larger than 5")

all elements in M are not larger than 5


## TLDR:
- всегда используйте встроенные в np функции;
- векторизуйте везде, где это возможно!

# 2.5. Numpy - I/O.

В данном случае у нас на выбор 2 опции - либо формат numpy, либо просто текстовый файл.

In [261]:
np.save("random.npy", M)

In [262]:
!cat random.npy

�NUMPYv{'descr': '<f8', 'fortran_order': False, 'shape': (3, 3), }                                                          
>�:��?����+�?�*���?Vu�
�J�?<�4X��?O3��?��� ��?�b~Ľ�?,��WN��?

In [263]:
np.load("random.npy")

array([[0.71499388, 0.72409148, 0.01867644],
       [0.2858131 , 0.58048634, 0.93078663],
       [0.3389969 , 0.12008312, 0.51627271]])

In [264]:
np.savetxt('random.csv', M, delimiter='\t')

In [265]:
! cat random.csv

7.149938815135231662e-01	7.240914834378769926e-01	1.867643942368146792e-02
2.858131033588809933e-01	5.804863352453888403e-01	9.307866320901697632e-01
3.389969016787631739e-01	1.200831230696660645e-01	5.162727085257521331e-01


In [266]:
np.loadtxt('random.csv')

array([[0.71499388, 0.72409148, 0.01867644],
       [0.2858131 , 0.58048634, 0.93078663],
       [0.3389969 , 0.12008312, 0.51627271]])

# 2.6 SciPy

### Разреженные матрицы

Compressed Sparse Column matrix

- Advantages of the CSC format
- - efficient arithmetic operations CSC + CSC, CSC * CSC, etc.
- - efficient column slicing
- - fast matrix vector products (CSR, BSR may be faster)
- Disadvantages of the CSC format
- - slow row slicing operations (consider CSR)
- - changes to the sparsity structure are expensive (consider LIL or DOK)

In [267]:
import numpy as np
from scipy.sparse import csc_matrix, csr_matrix

row = np.array([0, 2, 2, 0, 1, 2])
col = np.array([0, 0, 1, 2, 2, 2])
data = np.array([1, 2, 3, 4, 5, 6])
csc_matrix((data, (row, col)), shape=(3, 3))

<3x3 sparse matrix of type '<type 'numpy.int64'>'
	with 6 stored elements in Compressed Sparse Column format>

In [268]:
csc_matrix((data, (row, col)), shape=(3, 3)).toarray()

array([[1, 0, 4],
       [0, 0, 5],
       [2, 3, 6]])

Compressed Sparse Row matrix

- Advantages of the CSR format
- - efficient arithmetic operations CSR + CSR, CSR * CSR, etc.
- - efficient row slicing
- - fast matrix vector products
- Disadvantages of the CSR format
- - slow column slicing operations (consider CSC)
- - changes to the sparsity structure are expensive (consider LIL or DOK)

In [269]:
row = np.array([0, 0, 1, 2, 2, 2])
col = np.array([0, 2, 2, 0, 1, 2])
data = np.array([1, 2, 3, 4, 5, 6])
csr_matrix((data, (row, col)), shape=(3, 3)).toarray()

array([[1, 0, 2],
       [0, 0, 3],
       [4, 5, 6]])

### Методы оптимизации

In [270]:
from scipy.optimize import minimize

def rosen(x):
    """The Rosenbrock function"""
    return sum(100.0*(x[1:]-x[:-1]**2.0)**2.0 + (1-x[:-1])**2.0)

In [271]:
x0 = np.array([1.3, 0.7, 0.8, 1.9, 1.2])
res = minimize(rosen, x0, method='nelder-mead', options={'xtol': 1e-8, 'disp': True})
res

Optimization terminated successfully.
         Current function value: 0.000000
         Iterations: 339
         Function evaluations: 571


 final_simplex: (array([[1.        , 1.        , 1.        , 1.        , 1.        ],
       [1.        , 1.        , 1.        , 1.        , 1.        ],
       [1.        , 1.        , 1.        , 1.00000001, 1.00000001],
       [1.        , 1.        , 1.        , 1.        , 1.        ],
       [1.        , 1.        , 1.        , 1.        , 1.        ],
       [1.        , 1.        , 1.        , 1.        , 0.99999999]]), array([4.86115343e-17, 7.65182843e-17, 8.11395684e-17, 8.63263255e-17,
       8.64080682e-17, 2.17927418e-16]))
           fun: 4.861153433422115e-17
       message: 'Optimization terminated successfully.'
          nfev: 571
           nit: 339
        status: 0
       success: True
             x: array([1., 1., 1., 1., 1.])

In [272]:
res = minimize(lambda x: (x - 2.7) ** 2 + 3, x0=100, method='BFGS')
res

      fun: 3.0
 hess_inv: array([[0.49999996]])
      jac: array([0.])
  message: 'Optimization terminated successfully.'
     nfev: 21
      nit: 4
     njev: 7
   status: 0
  success: True
        x: array([2.69999999])

### Проверка стат-тестов

In [273]:
from scipy import stats
rvs = stats.norm.rvs(loc=5, scale=10, size=(50,2))
stats.ttest_1samp(rvs,5.0)

Ttest_1sampResult(statistic=array([-0.84119401, -0.8095138 ]), pvalue=array([0.40432578, 0.42213338]))

In [274]:
stats.ttest_1samp(rvs,0.0)

Ttest_1sampResult(statistic=array([2.96739532, 2.5570805 ]), pvalue=array([0.00463455, 0.01370275]))

# Задачки

- Создать "шахматную доску" на numpy:

```1 0 1 0 1
0 1 0 1 0
1 0 1 0 1
0 1 0 1 0
1 0 1 0 1```

- Создать случайный вектор и занулить три самых больших по модулю значения

- Диагональная матрица с квадратами натуральных чисел

- Змейка 

```[[ 1  6 11 16 21]
 [ 2  7 12 17 22]
 [ 3  8 13 18 23]
 [ 4  9 14 19 24]
 [ 5 10 15 20 25]]```
 
- Евклидово расстояние между вектором и всеми строчками матрицы

- Косинусное расстояние между вектором и всеми строчками матрицы. Косинусное расстояние для векторов
 